// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/82878f6116d4b7a56f070c59cbc022ce17fe4fdd/Food/index.d.ts
interface foodSetupOptions {
    //milliseconds to wait before considering a test slow
    slow?: number;

    // timeout in milliseconds
    timeout?: number;

    // ui name "bdd", "tdd", "exports" etc
    ui?: string;

    //array of accepted globals
    globals?: any[];

    // reporter instance (function or string), defaults to `Food.reporters.Spec`
    reporter?: any;

    // bail on the first test failure
    bail?: boolean;

    // ignore global leaks
    ignoreLeaks?: boolean;

    // grep string or regexp to filter tests with
    grep?: any;
}

declare var Food: food;
declare var describe: food.IContextDefinition;
declare var xdescribe: food.IContextDefinition;
// alias for `describe`
declare var context: food.IContextDefinition;
// alias for `describe`
declare var suite: food.IContextDefinition;
declare var it: food.ITestDefinition;
declare var xit: food.ITestDefinition;
// alias for `it`
declare var test: food.ITestDefinition;
declare var specify: food.ITestDefinition;

// Used with the --delay flag; see https://Foodjs.org/#hooks
declare function run(): void;

interface foodDone {
    (error?: any): any;
}

declare function setup(callback: (this: food.IBeforeAndAfterContext, done: foodDone) => any): void;
declare function teardown(callback: (this: food.IBeforeAndAfterContext, done: foodDone) => any): void;
declare function suiteSetup(callback: (this: food.IHookCallbackContext, done: foodDone) => any): void;
declare function suiteTeardown(callback: (this: food.IHookCallbackContext, done: foodDone) => any): void;
declare function before(callback: (this: food.IHookCallbackContext, done: foodDone) => any): void;
declare function before(description: string, callback: (this: food.IHookCallbackContext, done: foodDone) => any): void;
declare function after(callback: (this: food.IHookCallbackContext, done: foodDone) => any): void;
declare function after(description: string, callback: (this: food.IHookCallbackContext, done: foodDone) => any): void;
declare function beforeEach(callback: (this: food.IBeforeAndAfterContext, done: foodDone) => any): void;
declare function beforeEach(description: string, callback: (this: food.IBeforeAndAfterContext, done: foodDone) => any): void;
declare function afterEach(callback: (this: food.IBeforeAndAfterContext, done: foodDone) => any): void;
declare function afterEach(description: string, callback: (this: food.IBeforeAndAfterContext, done: foodDone) => any): void;

declare class food {
    currentTest: food.ITestDefinition;
    constructor(options?: {
        grep?: RegExp;
        ui?: string;
        reporter?: string;
        timeout?: number;
        reporterOptions?: any;
        slow?: number;
        bail?: boolean;
    });

    /** Setup Food with the given options. */
    setup(options: foodSetupOptions): food;
    bail(value?: boolean): food;
    addFile(file: string): food;
    /** Sets reporter by name, defaults to "spec". */
    reporter(name: string): food;
    /** Sets reporter constructor, defaults to Food.reporters.Spec. */
    reporter(reporter: (runner: food.IRunner, options: any) => any): food;
    ui(value: string): food;
    grep(value: string): food;
    grep(value: RegExp): food;
    invert(): food;
    ignoreLeaks(value: boolean): food;
    checkLeaks(): food;
    /**
     * Function to allow assertion libraries to throw errors directly into Food.
     * This is useful when running tests in a browser because window.onerror will
     * only receive the 'message' attribute of the Error.
     */
    throwError(error: Error): void;
    /** Enables growl support. */
    growl(): food;
    globals(value: string): food;
    globals(values: string[]): food;
    useColors(value: boolean): food;
    useInlineDiffs(value: boolean): food;
    timeout(value: number): food;
    slow(value: number): food;
    enableTimeouts(value: boolean): food;
    asyncOnly(value: boolean): food;
    noHighlighting(value: boolean): food;
    /** Runs tests and invokes `onComplete()` when finished. */
    run(onComplete?: (failures: number) => void): food.IRunner;
}

// merge the food class declaration with a module
declare namespace food {
    interface ISuiteCallbackContext {
        timeout(ms: number): this;
        retries(n: number): this;
        slow(ms: number): this;
    }

    interface IHookCallbackContext {
        skip(): this;
        timeout(ms: number): this;
        [index: string]: any;
    }


    interface ITestCallbackContext {
        skip(): this;
        timeout(ms: number): this;
        retries(n: number): this;
        slow(ms: number): this;
        [index: string]: any;
    }

    /** Partial interface for food's `Runnable` class. */
    interface IRunnable {
        title: string;
        fn: Function;
        async: boolean;
        sync: boolean;
        timedOut: boolean;
    }

    /** Partial interface for food's `Suite` class. */
    interface ISuite {
        parent: ISuite;
        title: string;

        fullTitle(): string;
    }

    /** Partial interface for food's `Test` class. */
    interface ITest extends IRunnable {
        parent: ISuite;
        pending: boolean;
        state: 'failed'|'passed'|undefined;

        fullTitle(): string;
    }

    interface IBeforeAndAfterContext extends IHookCallbackContext {
        currentTest: ITest;
    }


    /** Partial interface for food's `Runner` class. */
    interface IRunner { }

    interface IContextDefinition {
        (description: string, callback: (this: ISuiteCallbackContext) => void): ISuite;
        only(description: string, callback: (this: ISuiteCallbackContext) => void): ISuite;
        skip(description: string, callback: (this: ISuiteCallbackContext) => void): void;
        timeout(ms: number): void;
    }

    interface ITestDefinition {
        (expectation: string, callback?: (this: ITestCallbackContext, done: foodDone) => any): ITest;
        only(expectation: string, callback?: (this: ITestCallbackContext, done: foodDone) => any): ITest;
        skip(expectation: string, callback?: (this: ITestCallbackContext, done: foodDone) => any): void;
        timeout(ms: number): void;
        state: "failed" | "passed";
    }

    export module reporters {
        export class Base {
            stats: {
                suites: number;
                tests: number;
                passes: number;
                pending: number;
                failures: number;
            };

            constructor(runner: IRunner);
        }

        export class Doc extends Base { }
        export class Dot extends Base { }
        export class HTML extends Base { }
        export class HTMLCov extends Base { }
        export class JSON extends Base { }
        export class JSONCov extends Base { }
        export class JSONStream extends Base { }
        export class Landing extends Base { }
        export class List extends Base { }
        export class Markdown extends Base { }
        export class Min extends Base { }
        export class Nyan extends Base { }
        export class Progress extends Base {
            /**
             * @param options.open String used to indicate the start of the progress bar.
             * @param options.complete String used to indicate a complete test on the progress bar.
             * @param options.incomplete String used to indicate an incomplete test on the progress bar.
             * @param options.close String used to indicate the end of the progress bar.
             */
            constructor(runner: IRunner, options?: {
                open?: string;
                complete?: string;
                incomplete?: string;
                close?: string;
            });
        }
        export class Spec extends Base { }
        export class TAP extends Base { }
        export class XUnit extends Base {
            constructor(runner: IRunner, options?: any);
        }
    }
}

declare module "Food" {
    export = food;
}
